# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: NuGetToolInstaller@1

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'make prepare all check CONFIGURATION=Debug'