trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'apidoctools.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: Bash@3
  displayName: Nuget restore
  inputs:
    targetType: 'inline'
    script: |
      git submodule update --init --recursive
      nuget restore apidoctools.sln
      nuget install NUnit.Console -version 3.6.0 -NoCache -o packages

- task: MSBuild@1
  displayName: Build mdoc
  inputs:
    solution: '$(solution)'
    msbuildArguments: '/p:RunCodeAnalysis=False,RunCodeAnalysisOnThisProject=False'
    configuration: '$(buildConfiguration)'

- task: EsrpCodeSigning@1
  displayName: Sign executable and dll files
  inputs:
        ConnectedServiceName: 'CodeSigning-APEX'
        FolderPath: 'bin/$(buildConfiguration)'
        UseMinimatch: true
        signConfigType: inlineSignParams
        SessionTimeout: '60'
        MaxConcurrency: '100'
        MaxRetryAttempts: '5'
        Pattern: |
            *.dll
            *.exe
        inlineOperation: |
         [
            {
              "KeyCode": "CP-236167",
              "OperationSetCode": "SigntoolSign",
              "parameters": [
                {
                  "parameterName": "OpusName",
                  "parameterValue": "Microsoft"
                },
                {
                  "parameterName": "OpusInfo",
                  "parameterValue": "http://www.microsoft.com"
                },
                {
                  "parameterName": "PageHash",
                  "parameterValue": "/NPH"
                },
                {
                  "parameterName": "TimeStamp",
                  "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                },
                {
                  "parameterName": "FileDigest",
                  "parameterValue": "/fd \"SHA256\""
                }
              ],
              "ToolName": "sign",
              "ToolVersion": "1.0"
            },
            {
              "KeyCode": "CP-236167",
              "OperationSetCode": "SigntoolVerify",
              "Parameters": [
                {
                  "parameterName": "VerifyAll",
                  "parameterValue": "/all"
                }
              ],
              "ToolName": "sign",
              "ToolVersion": "1.0"
            }
          ]

- task: ArchiveFiles@1
  displayName: Archive mdoc files
  inputs:
        rootFolder: 'bin/$(buildConfiguration)'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/zips/site-$(Build.BuildId).zip'

- task: PublishPipelineArtifact@1
  displayName: 'Publish mdoc Artifact'
  inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/zips'
        artifact: 'mdoc.Artifact'