trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  mdocPath: 'bin/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet tool'

- task: Bash@3
  displayName: 'Run unit tests'
  inputs:
    targetType: 'inline'
    script: 'make prepare all check CONFIGURATION=Debug'

- task: MSBuild@1
  displayName: 'Building mdoc in $(buildConfiguration) mode'
  inputs:
    solution: 'apidoctools.sln'
    msbuildArguments: '/p:RunCodeAnalysis=False,RunCodeAnalysisOnThisProject=False'
    configuration: '$(buildConfiguration)'

- task: ArchiveFiles@1
  displayName: Archive mdoc files
  inputs:
        rootFolder: '$(mdocPath)'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/zips/mdoc-$(Build.BuildId).zip'

- task: PublishPipelineArtifact@1
  displayName: 'Publish mdoc atifact'
  inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/zips'
        artifact: 'mdoc.Artifact'