trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  mdocPath: 'bin/$(buildConfiguration)'

stages:
  - stage: 'Build'
    jobs:
    - job: 'UnitTest_Build_CodeSigning_Archive'
      steps:
      - task: NuGetToolInstaller@1
        displayName: 'Install NuGet Tool'

      - task: Bash@3
        displayName: 'Run Unit Tests'
        inputs:
          targetType: 'inline'
          script: 'make prepare all check CONFIGURATION=Debug'

      - task: MSBuild@1
        displayName: 'Building mdoc In $(buildConfiguration) Mode'
        inputs:
          solution: 'apidoctools.sln'
          msbuildArguments: '/p:RunCodeAnalysis=False,RunCodeAnalysisOnThisProject=False'
          configuration: '$(buildConfiguration)'

      - task: ArchiveFiles@1
        displayName: Archive mdoc Files
        inputs:
              rootFolder: '$(mdocPath)'
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)/zips/mdoc-$(Build.BuildId).zip'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish mdoc Atifact'
        inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/zips'
              artifact: 'mdoc.Artifact'