trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  mdocPath: 'bin/Debug'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet tool'

- task: Bash@3
  displayName: Build mdoc and run unit tests
  inputs:
    targetType: 'inline'
    script: 'make prepare all check CONFIGURATION=Debug'

- task: ArchiveFiles@1
  displayName: Archive mdoc files
  inputs:
        rootFolder: '$(mdocPath)'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/zips/mdoc-$(Build.BuildId).zip'

- task: PublishPipelineArtifact@1
  displayName: 'Publish mdoc atifact'
  inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/zips'
        artifact: 'mdoc.Artifact'