trigger:
- main
- develop

pr: none

resources:
  repositories:
    - repository: templates
      type: git
      name: Engineering/api-doc-tools
      ref: main

extends:
  template: .pipelines/bootstrap/trigger-Official.yml@templates ###