trigger: none

pr:
  autoCancel: true
  drafts: false
  branches:
    include:
      - main
      - develop

resources:
  repositories:
    - repository: templates
      type: git
      name: Engineering/api-doc-tools
      ref: main

extends:
  template: .pipelines/bootstrap/trigger-Buddy.yml@templates