trigger:
- develop
- xdanni-test

pr:
- main
- develop

resources:
  repositories:
    - repository: templates
      type: git
      name: Engineering/api-doc-tools
      ref: xdanni-test

extends:
  template: .pipelines/bootstrap/trigger-Buddy.yml@templates