name: Tests

on:
  push:
    branches: [ main, master, dev/** ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest] # Linux is having Telemetry issues
        configuration: [Release] # mono F# generates different APIs in Debug vs Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.x'

    - name: Install Mono (required for mdoc tests) - Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt install ca-certificates gnupg
        sudo gpg --homedir /tmp --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        sudo chmod +r /usr/share/keyrings/mono-official-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt update
        sudo apt install mono-complete mono-vbnc

    - name: Install Mono (required for mdoc tests) - macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install --cask mono-mdk

    - name: Restore dependencies
      run: dotnet restore apidoctools.sln

    - name: Build
      run: dotnet build apidoctools.sln -c ${{ matrix.configuration }} --no-restore

    - name: Run .NET tests
      run: dotnet test apidoctools.sln -c ${{ matrix.configuration }} --no-build --verbosity normal --logger trx --collect "XPlat Code Coverage"

    - name: Run mdoc tests
      if: matrix.os != 'windows-latest'
      run: make check-mdoc CONFIGURATION=${{ matrix.configuration }}

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.configuration }}
        path: |
          **/TestResults/**
        retention-days: 30

    - name: Upload code coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: code-coverage-${{ matrix.os }}-${{ matrix.configuration }}
        path: |
          **/TestResults/**/coverage.*
        retention-days: 30

    - name: Report test results
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: Test Report (${{ matrix.os }})
        path: '**/*.trx'
        reporter: dotnet-trx
